spring.application.name=duas-marias

# H2 Database
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# JPA
# spring.jpa.hibernate.ddl-auto=update


# H2 Console
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console


spring.datasource.url=jdbc:mysql://localhost:3306/duas_marias_ecommerce
spring.datasource.username=root
spring.datasource.password=k1cicawu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect




# IMAGES
project.image=images/


spring.app.jwtSecret=mySecretKey123912738kjdsfksjfdssdgskdmgksdml
spring.app.jwtExpirationMs=30000000
spring.app.jwtCookieName=springBootEcom

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.org.springframework.security=DEBUG
logging.level.org.com.ecommerce.duas_marias=DEBUG